create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password text not null,
  device_id text unique not null,
  device_name text not null default 'RIDE X',
  full_name text,
  emergency_contact1_name text,
  emergency_contact1_phone text,
  emergency_contact2_name text,
  emergency_contact2_phone text,
  birthday text,
  address text,
  is_active boolean not null default true,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pairing_codes (
  code text primary key,
  owner_user_id bigint not null references public.users(id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  accuracy double precision,
  device_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.code_usage (
  id bigint generated by default as identity primary key,
  code text not null references public.pairing_codes(code) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  device_id text not null,
  created_at timestamptz not null default now(),
  unique (code, user_id, device_id)
);

create table if not exists public.device_tokens (
  device_id text primary key,
  fcm_token text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  device_name text not null,
  message text not null,
  type text not null default 'crash',
  created_at timestamptz not null default now()
);

create table if not exists public.sensor_readings (
  id bigint generated by default as identity primary key,
  device_id text,
  accelerometer jsonb,
  gyroscope jsonb,
  gps jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.crash_events (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  device_id text,
  device_name text not null,
  rider_name text,
  crash_time timestamptz not null,
  message text not null,
  g_force double precision not null default 0,
  accel_x double precision not null default 0,
  accel_y double precision not null default 0,
  accel_z double precision not null default 0,
  gyro_x double precision not null default 0,
  gyro_y double precision not null default 0,
  gyro_z double precision not null default 0,
  temperature double precision,
  gps_latitude double precision,
  gps_longitude double precision,
  gps_altitude double precision,
  emergency_contact1_name text,
  emergency_contact1_phone text,
  emergency_contact2_name text,
  emergency_contact2_phone text,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.pairing_codes enable row level security;
alter table public.code_usage enable row level security;
alter table public.device_tokens enable row level security;
alter table public.notifications enable row level security;
alter table public.sensor_readings enable row level security;
